apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: village
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: google-cloud-key
            secret:
              secretName: village-key
          containers:
          - name: village
            image: gcr.io/village/village
            volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          restartPolicy: OnFailure