// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type House int32

const (
	House_UNKNOWN_HOUSE         House = 0
	House_VICTORIA_STATION      House = 1
	House_TEA_SHOPPE            House = 2
	House_SPICE_MARKET          House = 3
	House_MARIONETTES           House = 4
	House_FELLOWSHIP_PORTERS    House = 5
	House_FEZZIWIG_WAREHOUSE    House = 6
	House_FEZZIWIG_WAREHOUSE_2  House = 7
	House_CROOKED_FENCE_COTTAGE House = 8
	House_BUTCHER               House = 9
	House_CUROSITY_SHOP         House = 10
	House_BAKERY                House = 11
)

var House_name = map[int32]string{
	0:  "UNKNOWN_HOUSE",
	1:  "VICTORIA_STATION",
	2:  "TEA_SHOPPE",
	3:  "SPICE_MARKET",
	4:  "MARIONETTES",
	5:  "FELLOWSHIP_PORTERS",
	6:  "FEZZIWIG_WAREHOUSE",
	7:  "FEZZIWIG_WAREHOUSE_2",
	8:  "CROOKED_FENCE_COTTAGE",
	9:  "BUTCHER",
	10: "CUROSITY_SHOP",
	11: "BAKERY",
}

var House_value = map[string]int32{
	"UNKNOWN_HOUSE":         0,
	"VICTORIA_STATION":      1,
	"TEA_SHOPPE":            2,
	"SPICE_MARKET":          3,
	"MARIONETTES":           4,
	"FELLOWSHIP_PORTERS":    5,
	"FEZZIWIG_WAREHOUSE":    6,
	"FEZZIWIG_WAREHOUSE_2":  7,
	"CROOKED_FENCE_COTTAGE": 8,
	"BUTCHER":               9,
	"CUROSITY_SHOP":         10,
	"BAKERY":                11,
}

func (x House) String() string {
	return proto.EnumName(House_name, int32(x))
}

func (House) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{0}
}

type Config struct {
	HousePins            map[uint32]House `protobuf:"bytes,1,rep,name=house_pins,json=housePins,proto3" json:"house_pins,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=House"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetHousePins() map[uint32]House {
	if m != nil {
		return m.HousePins
	}
	return nil
}

// ChangeLight changes the color / brightness of multucolor LEDs.
type ChangeLight struct {
	// The house to control.
	House House `protobuf:"varint,1,opt,name=house,proto3,enum=House" json:"house,omitempty"`
	// The white amount for the house, 0 - 100.
	White uint32 `protobuf:"varint,2,opt,name=white,proto3" json:"white,omitempty"`
	// The red amount for the house, 0 - 100.
	Red                  uint32   `protobuf:"varint,3,opt,name=red,proto3" json:"red,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeLight) Reset()         { *m = ChangeLight{} }
func (m *ChangeLight) String() string { return proto.CompactTextString(m) }
func (*ChangeLight) ProtoMessage()    {}
func (*ChangeLight) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{1}
}

func (m *ChangeLight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeLight.Unmarshal(m, b)
}
func (m *ChangeLight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeLight.Marshal(b, m, deterministic)
}
func (m *ChangeLight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeLight.Merge(m, src)
}
func (m *ChangeLight) XXX_Size() int {
	return xxx_messageInfo_ChangeLight.Size(m)
}
func (m *ChangeLight) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeLight.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeLight proto.InternalMessageInfo

func (m *ChangeLight) GetHouse() House {
	if m != nil {
		return m.House
	}
	return House_UNKNOWN_HOUSE
}

func (m *ChangeLight) GetWhite() uint32 {
	if m != nil {
		return m.White
	}
	return 0
}

func (m *ChangeLight) GetRed() uint32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func init() {
	proto.RegisterEnum("House", House_name, House_value)
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterMapType((map[uint32]House)(nil), "Config.HousePinsEntry")
	proto.RegisterType((*ChangeLight)(nil), "ChangeLight")
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor_0dff099eb2e3dfdb) }

var fileDescriptor_0dff099eb2e3dfdb = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x6f, 0xd3, 0x30,
	0x1c, 0xc5, 0x71, 0x4b, 0x33, 0xf6, 0x0f, 0x2d, 0xc6, 0x2a, 0x53, 0x40, 0x1c, 0xaa, 0x9d, 0x2a,
	0x0e, 0x3d, 0x14, 0x21, 0x21, 0x6e, 0x9e, 0xf7, 0xdf, 0x62, 0xb5, 0x8b, 0x23, 0xdb, 0xa5, 0xda,
	0x2e, 0x56, 0xa1, 0xa1, 0x89, 0x60, 0xc9, 0x94, 0x64, 0xa0, 0x7d, 0x00, 0xbe, 0x31, 0x1f, 0x00,
	0x25, 0x16, 0x12, 0x88, 0x9b, 0xdf, 0x7b, 0x7a, 0xef, 0x67, 0xcb, 0x30, 0xf9, 0x5c, 0xdd, 0xde,
	0xee, 0xca, 0x7d, 0xb3, 0xb8, 0xab, 0xab, 0xb6, 0x3a, 0xfd, 0x49, 0x20, 0x10, 0x55, 0xf9, 0xa5,
	0x38, 0xb0, 0x77, 0x00, 0x79, 0x75, 0xdf, 0x64, 0xee, 0xae, 0x28, 0x9b, 0x88, 0xcc, 0x86, 0xf3,
	0x70, 0x79, 0xb2, 0xf0, 0xe1, 0x22, 0xee, 0x92, 0xb4, 0x28, 0x1b, 0x2c, 0xdb, 0xfa, 0x41, 0x1f,
	0xe7, 0x7f, 0xf4, 0xab, 0x73, 0x98, 0xfc, 0x1b, 0x32, 0x0a, 0xc3, 0xaf, 0xd9, 0x43, 0x44, 0x66,
	0x64, 0x3e, 0xd6, 0xdd, 0x91, 0xbd, 0x86, 0xd1, 0xf7, 0xdd, 0xb7, 0xfb, 0x2c, 0x1a, 0xcc, 0xc8,
	0x7c, 0xb2, 0x0c, 0xfc, 0x9c, 0xf6, 0xe6, 0x87, 0xc1, 0x7b, 0x72, 0x6a, 0x20, 0x14, 0xf9, 0xae,
	0x3c, 0x64, 0xeb, 0xe2, 0x90, 0xb7, 0x5d, 0xa1, 0x27, 0xf4, 0x23, 0x7f, 0x15, 0x7a, 0x93, 0x4d,
	0x61, 0xf4, 0x23, 0x2f, 0x5a, 0x3f, 0x37, 0xd6, 0x5e, 0x74, 0xd8, 0x3a, 0xdb, 0x47, 0x43, 0x8f,
	0xad, 0xb3, 0xfd, 0x9b, 0x5f, 0x04, 0x46, 0x7d, 0x91, 0x3d, 0x87, 0xf1, 0x26, 0x59, 0x25, 0x6a,
	0x9b, 0xb8, 0x58, 0x6d, 0x0c, 0xd2, 0x47, 0x6c, 0x0a, 0xf4, 0xa3, 0x14, 0x56, 0x69, 0xc9, 0x9d,
	0xb1, 0xdc, 0x4a, 0x95, 0x50, 0xc2, 0x26, 0x00, 0x16, 0xb9, 0x33, 0xb1, 0x4a, 0x53, 0xa4, 0x03,
	0x46, 0xe1, 0xa9, 0x49, 0xa5, 0x40, 0x77, 0xc5, 0xf5, 0x0a, 0x2d, 0x1d, 0xb2, 0x67, 0x10, 0x5e,
	0x71, 0x2d, 0x55, 0x82, 0xd6, 0xa2, 0xa1, 0x8f, 0xd9, 0x09, 0xb0, 0x0b, 0x5c, 0xaf, 0xd5, 0xd6,
	0xc4, 0x32, 0x75, 0xa9, 0xd2, 0x16, 0xb5, 0xa1, 0x23, 0xef, 0xdf, 0xdc, 0xc8, 0xad, 0xbc, 0x74,
	0x5b, 0xae, 0xd1, 0x83, 0x03, 0x16, 0xc1, 0xf4, 0x7f, 0xdf, 0x2d, 0xe9, 0x11, 0x7b, 0x09, 0x2f,
	0x84, 0x56, 0x6a, 0x85, 0xe7, 0xee, 0x02, 0x13, 0x81, 0x4e, 0x28, 0x6b, 0xf9, 0x25, 0xd2, 0x27,
	0x2c, 0x84, 0xa3, 0xb3, 0x8d, 0x15, 0x31, 0x6a, 0x7a, 0xdc, 0xbd, 0x46, 0x6c, 0xb4, 0x32, 0xd2,
	0x5e, 0xf7, 0x37, 0xa5, 0xc0, 0x00, 0x82, 0x33, 0xbe, 0x42, 0x7d, 0x4d, 0xc3, 0x4f, 0x41, 0xff,
	0xb5, 0x6f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x32, 0xd1, 0xd1, 0xec, 0x01, 0x00, 0x00,
}
