/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "commands.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Config, Config, AUTO)


PB_BIND(Config_HousePinsEntry, Config_HousePinsEntry, AUTO)


PB_BIND(ChangeLight, ChangeLight, AUTO)




