/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Wed Dec 11 19:51:43 2019. */

#include "commands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Config_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, Config, house_pins, house_pins, &Config_HousePinsEntry_fields),
    PB_LAST_FIELD
};

const pb_field_t Config_HousePinsEntry_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Config_HousePinsEntry, key, key, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, Config_HousePinsEntry, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t ChangeLight_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ChangeLight, house, house, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ChangeLight, white, house, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ChangeLight, red, white, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
