/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Wed Dec 11 19:51:43 2019. */

#ifndef PB_COMMANDS_PB_H_INCLUDED
#define PB_COMMANDS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _House {
    House_UNKNOWN_HOUSE = 0,
    House_VICTORIA_STATION = 1,
    House_TEA_SHOPPE = 2,
    House_SPICE_MARKET = 3,
    House_MARIONETTES = 4,
    House_FELLOWSHIP_PORTERS = 5,
    House_FEZZIWIG_WAREHOUSE = 6,
    House_FEZZIWIG_WAREHOUSE_2 = 7,
    House_CROOKED_FENCE_COTTAGE = 8,
    House_BUTCHER = 9,
    House_CUROSITY_SHOP = 10
} House;
#define _House_MIN House_UNKNOWN_HOUSE
#define _House_MAX House_CUROSITY_SHOP
#define _House_ARRAYSIZE ((House)(House_CUROSITY_SHOP+1))

/* Struct definitions */
typedef struct _Config {
    pb_callback_t house_pins;
/* @@protoc_insertion_point(struct:Config) */
} Config;

typedef struct _ChangeLight {
    House house;
    uint32_t white;
    uint32_t red;
/* @@protoc_insertion_point(struct:ChangeLight) */
} ChangeLight;

typedef struct _Config_HousePinsEntry {
    uint32_t key;
    House value;
/* @@protoc_insertion_point(struct:Config_HousePinsEntry) */
} Config_HousePinsEntry;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Config_init_default                      {{{NULL}, NULL}}
#define Config_HousePinsEntry_init_default       {0, _House_MIN}
#define ChangeLight_init_default                 {_House_MIN, 0, 0}
#define Config_init_zero                         {{{NULL}, NULL}}
#define Config_HousePinsEntry_init_zero          {0, _House_MIN}
#define ChangeLight_init_zero                    {_House_MIN, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Config_house_pins_tag                    1
#define ChangeLight_house_tag                    1
#define ChangeLight_white_tag                    2
#define ChangeLight_red_tag                      3
#define Config_HousePinsEntry_key_tag            1
#define Config_HousePinsEntry_value_tag          2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Config_fields[2];
extern const pb_field_t Config_HousePinsEntry_fields[3];
extern const pb_field_t ChangeLight_fields[4];

/* Maximum encoded size of messages (where known) */
/* Config_size depends on runtime parameters */
#define Config_HousePinsEntry_size               8
#define ChangeLight_size                         14

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COMMANDS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
